### ISSUE TITLE
struggling blind artist 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#102]
The notion of "struggling blind artist" is not great... there are no "blind artists", just "artists". 

Should say: 

> James, an artist, requires that the musical score within his publication be rendered in braille music.

**Comment by iherman** [comment]
I would agree

@hlflanagan @clapierre, are you o.k. with the proposed changes?

**Comment by mattgarrish** [comment]
Wouldn't it be more appropriate to call him a "musician" if he needs to read a braille musical score?

I'm a little confused by the requirement, though. Does he want to play the music back or read it, or both? (What is "rendered as braille music"?)

As a suggestion (which might well be wrong):

"James, a musician, requires that the musical score within a publication come preformatted in braille music notation in order to read it, as he uses freely available assistive technology which does not have braille music translations built in."

But even this is kind of confusing, since why is this pertinent to a multimedia section? If the score is a graphic, where does translation come into play? If it's a text score, I wouldn't really consider it multimedia.

**Comment by marcoscaceres** [comment]
heh, we should just drop the label entirely "James wants to...".

**Comment by iherman** [comment]
@marcoscaceres I am not sure whether you propose to remove that use case entirely, or whether to go along with @mattgarrish's formulation...

**Comment by mattgarrish** [comment]
James could be an engineer who likes music and it really doesn't change the use case in any way. But these use cases are "humanized", so I don't have a big issue with keeping the label.

I'll accept that braille falls into this category as "mixed media" on re-read, but the lead-in focuses on audio, video and graphics and then there are only two very brief use cases related to those three. I missed the connection.

And sorry for belabouring this, but you might also want to adjust this paragraph:

> All concepts and structures related to a PWP should enable the creation and/or production of video or audio rendering; all the audio, video, and graphics content must be treated with the same attention as all other content.

You might generalize the focus on audio/video/graphics so it's less at odds with the braille cases. I'm not sure what to say about "must be treated with the same attention as all other content", except that it would probably help to tighten to a more actionable statement.

**Comment by lrosenthol** [comment]
incorporated into [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe)
