### ISSUE TITLE
4.1 Dynamic Content

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#114]
> Req. 19: The PWP needs to have an explicit “offline mode” alternative.

This whole section is also really misguided and seems to make some strange assumptions about how browsers and web applications work. 

Please remove it.

**Comment by lrosenthol** [comment]
@marcoscaceres could you be more specific about what you see as strange.  Also considering that a PWP consumer need not be a browser or a web application.

**Comment by marcoscaceres** [comment]
> @marcoscaceres could you be more specific about what you see as strange. 

Sure: 

> It is possible that certain items will be dynamic, requiring the use of an external resource (or server) to provide the data. In offline mode, the user may want to be alerted that content could not be obtained, 

As it reads, this assumes that the user agent will alert the user if certain bits of the app break. That is impossible to do, because sometimes sites will rely on network exceptions to fetch things from the cache. 

> or be shown some fallback set of data.

As we already do, for instance when images break. 

> In this case, being able to specify an explicit “no-connectivity” or "offline-mode" alternative would allow the publication author to have more control over the user's experience and replace a potential error-display with a limited subset of a good experience.

This is not how it works in practice: the developer has control over both online and offline experience, and can switch and recover from either interchangeably. In other words, there is no "on-line" and "off-line": there is strategies to deal with either, and means to recover when things go bad.  

>  Also considering that a PWP consumer need not be a browser or a web application.

If it's built on HTML, then it MUST be a browser (well, browser engine)? Things that consume HTML/CSS/JS are a browser engine - so it has to be a browser of some sort, no?

**Comment by baldurbjarnason** [comment]
> If it's built on HTML, then it MUST be a browser (well, browser engine)? Things that consume HTML/CSS/JS are a browser engine - so it has to be a browser of some sort, no?

Based on what I've read on the DPUB list (e.g. insistence on packaging, using the term "reading agent", insistence on the existence of non-browser clients, continuity with EPUB, etc.) my impression is that some participants in this process are hoping that PWPs become the next version of ePub, if not actually ePub 4 then a conceptual successor to ePub 3.1. Hence the 'PWP consumers might not be a browser' comments.

**Comment by marcoscaceres** [comment]
> PWP consumers might not be a browser' 

But all the readers use browser engines, no? Like Kindle uses WebKit and iBooks uses WebKit, and so on.

**Comment by iherman** [comment]
> >    PWP consumers might not be a browser'
> 
> But all the readers use browser engines, no? Like Kindle uses WebKit and iBooks uses WebKit, and so on.

That is, I believe, correct, at least it will become more and more so. There may be some older ebook reader software that did its development from scratch (our implementer colleagues on the list may know more) but I am almost sure that all current and future developments will be based on one of the core engines (or use the superstructure on top of those provided by [Readium](http://readium.org/))

**Comment by iherman** [comment]
(for admin, this is closely related to issue #113)

Re-discussing how to formulate and think about states is now on the TPAC F2F agenda.

**Comment by sideshowbarker** [comment]
As @marcoscaceres alludes to in https://github.com/w3c/dpub-pwp-ucr/issues/114#issuecomment-247259303 I think it would help if the group documents somewhere that its proposals are targeted for implementation in “browser engines” (just as all other technologies we develop for the Web runtime are).

The distinction between “browser” and “browser engine” is important because while there are many different browsers, there are currently only four major browser engines (Gecko, Blink, Edge, and WebKit) that implement the core features of the Web runtime (HTML, CSS, DOM, JavaScript, Fetch and XHR, the Web-security model [same-origin policy], etc.).

And our specifications do not define browser behavior, they define browser-engine behavior; what I mean is we don’t have specs that say things like “the browser must provide an address bar” or “a browser must be able to display documents in multiple windows at the same time” or other things like that which relate only to the browser UI or browser chrome. Instead we only define what browser engines must do, and we leave it up to vendors to decide how their software exposes the underlying features of the engine.

So a browser can just be a very simple shell or wrapper around and browser engine to expose the (standard) features of the underlying engine.

And a Web-runtime user agent can be built around a browser engine without necessarily being seen as a Web browser. It could for example be a user agent with UI features specialized for reading collections of documents more easily. But if it is, the underlying engine still needs to conform to the requirements for browser engines defined in the core specifications for the Web runtime—for example, in needs to conform to the Web security model (follow the same-origin policy).

**Comment by sideshowbarker** [comment]
> Based on what I've read on the DPUB list (e.g. insistence on packaging, using the term "reading agent", insistence on the existence of non-browser clients, continuity with EPUB, etc.) my impression is that some participants in this process are hoping that PWPs become the next version of ePub, if not actually ePub 4 then a conceptual successor to ePub 3.1. Hence the 'PWP consumers might not be a browser' comments.

That continues to be a fundamental problem with this use-case-and-requirements document  as currently written: Its title and framing make it seem like a use-case-and-requirements document for EPUB (which is maybe not surprising [given its actual provenance](https://w3c.github.io/epubweb/)), just by a different name (PWP).

So I think this group needs to decide if it’s really trying to solve problems for users in the best way possible using the features of the Web or if instead what it’s really doing is trying to bring EPUB (or the next version of EPUB) to the Web while still keeping it all working with the legacy of off-Web reading systems and off-Web distribution that has been built up previously around “e-books”.

And if that’s what the goal is, it doesn’t really help to avoid explicitly mentioning EPUB and otherwise paper over it all with vaguer words about “packaging“ and “distribution“ (which are still just as foreign to the Web and to user experience of the Web as “EPUB” is). It still shows through pretty obviously in places like particular sections of this use-case-and-requirements document.

**Comment by lrosenthol** [comment]
@sideshowbarker Others in the group may weigh in differently, but I will give you my take on what I believe we are trying to accomplish.

I see the goal of PWP as an way to enable uses (from the church secretary though to the professional publisher) to be able to author and distribute, via any mechanism that they choose, a "document" or "publication" that uses the OWP to represent that content.

Since the "any mechanism" could be either online (eg hosted on a 'web server' somewhere) or offline (eg. sitting on a 'local' disk), it is also possible (probable) that any given PWP could go between these two "states" at any time.

So with that in mind, you can see why we talk about Portability, and also the Web (both in its full manner as well as simply the OWP technology stack).

**Comment by marcoscaceres** [comment]
> Since the "any mechanism" could be either online (eg hosted on a 'web server' somewhere) or offline (eg. sitting on a 'local' disk), it is also possible (probable) that any given PWP could go between these two "states" at any time.

That's fine. The web handles this already. We don't need to discuss it further because it's a requirement you already get for free.

**Comment by lrosenthol** [comment]
Please explain how "the web handles this already".

How can I email a web site (NOT a link - but the actual site!) to someone?

**Comment by tsiegman-wiley** [comment]
Going back to @baldurbjarnason  [comments](https://github.com/w3c/dpub-pwp-ucr/issues/114#issuecomment-247256579) and @sideshowbarker's question: 

> Based on what I've read on the DPUB list (e.g. insistence on packaging, using the term "reading agent", insistence on the existence of non-browser clients, continuity with EPUB, etc.) my impression is that some participants in this process are hoping that PWPs become the next version of ePub, if not actually ePub 4 then a conceptual successor to ePub 3.1. Hence the 'PWP consumers might not be a browser' comments.

We have not fleshed out completely what will happen next in this Group. However, several of us have spoken about creating more than one document. I would like to see something along the lines of an umbrella spec for Packaging/Bundling/API-ification of Collected Stuff. I have high hopes that this will be rely heavily on [Web App Manifest](https://www.w3.org/TR/appmanifest/) and Service Workers. I envision EPUB.Future as a profile/derivative of this umbrella (merger discussions, pending).

**Comment by TzviyaSiegman** [comment]
Don't you hate it when the wrong version of yourself posts on GitHub? That should have been written by this version of me.

**Comment by marcoscaceres** [comment]
@lrosenthol, 

> Please explain how "the web handles this already".

I was referring to "offline" and "online", in the sense that we can handle network errors. I think you are using "offline" to mean "off-web". 

> How can I email a web site (NOT a link - but the actual site!) to someone?

You can't. That's a feature of the Web - or what makes the Web, the Web.

**Comment by lrosenthol** [comment]
> You can't. That's a feature of the Web - or what makes the Web, the Web.

And I think this is also where there is a clear breakdown between your position and those of many of us.  We see the web as a set of technologies generically referred to as the Open Web Platform (OWP) - HTML, CSS, etc. - that can be used in numerous ways.  We are not restricting ourselves to only their use when "hosted" on the internet.

**Comment by marcoscaceres** [comment]
> And I think this is also where there is a clear breakdown between your position and those of many of us. We see the web as a set of technologies generically referred to as the Open Web Platform (OWP) - HTML, CSS, etc. - that can be used in numerous ways. We are not restricting ourselves to only their use when "hosted" on the internet.

I'm trying to convince this group that you can't do that: You can't take the HTTP(S) out of the web platform and expect it to work: it works as a cohesive whole. There is no piece-meal, we only want HTML, CSS, and JS, but we will ignore the HTTP part or replace it with a zip file. It simply breaks. 

It's all or nothing.

**Comment by lrosenthol** [comment]
> I'm trying to convince this group that you can't do that

And we are trying to convince you that you are wrong - looks like we will simply agree to disagree.

**Comment by marcoscaceres** [comment]
> And we are trying to convince you that you are wrong - looks like we will simply agree to disagree.

No, that's completely unacceptable, @lrosenthol. This isn't about opinions: we have the technology to  prove one way or another that the requirements can or cannot be met. 

This is not a "agree to disagree" thing. This is "show me the, um, book!" kinda thing.

**Comment by lrosenthol** [comment]
> This is not a "agree to disagree" thing. This is "show me the, um, book!" kinda thing.

Happy to do so.

But the same applies to you...

**Comment by marcoscaceres** [comment]
@lrosenthol, I was going to ask if one of the publishers has a book we could work from? @dauwhe, can we use that version of Moby Dick that you have? It would be awesome to have a real book and permission to experiment with it.

**Comment by dauwhe** [comment]
@marcoscaceres please take anything you want from https://github.com/dauwhe/epub-zero/tree/gh-pages/acme-publishing/MobyDick!

**Comment by marcoscaceres** [comment]
🎁🎅Christmas in September! 🍾🚨🎉

**Comment by HadrienGardeur** [comment]
> If it's built on HTML, then it MUST be a browser (well, browser engine)? Things that consume HTML/CSS/JS are a browser engine - so it has to be a browser of some sort, no?

Audiobooks and comics are also publications and they rely on audio files and images, not necessarily HTML.

For additional examples (based on the on-going work on EPUB BFF) you can take a look at: https://github.com/HadrienGardeur/webpub-manifest/tree/master/examples

I've also started a document that focus on the differences in requirements between apps and publications: https://github.com/HadrienGardeur/webpub-manifest/wiki/Web-App-Manifest-vs-Web-Publication-Manifest

**Comment by marcoscaceres** [comment]
> On 27 Sep. 2016, at 2:51 am, Hadrien Gardeur notifications@github.com wrote:
> 
> If it's built on HTML, then it MUST be a browser (well, browser engine)? Things that consume HTML/CSS/JS are a browser engine - so it has to be a browser of some sort, no?
> 
> Audiobooks and comics are also publications and they rely on audio files and images, not necessarily HTML.

For Audio books, those are embedded media. They absolutely rely on HTML (audio element) and the forthcoming Media Session API we are cooking up: https://wicg.github.io/mediasession/

Comics is images and layout - but def can be done with HTML... upcoming CSS Grids will also help. 

> For additional examples (based on the on-going work on EPUB BFF) you can take a look at: https://github.com/dauwhe/epub31-bff/tree/master/examples
> 
> I've also started a document that focus on the differences in requirements between apps and publications: https://github.com/dauwhe/epub31-bff/wiki/Web-App-Manifest-vs-Web-Publication-Manifest

Awesome! Will have a look!

**Comment by HadrienGardeur** [comment]
> For Audio books, those are embedded media. They absolutely rely on HTML (audio element) and the forthcoming Media Session API we are cooking up: https://wicg.github.io/mediasession/

Thanks for the link to the Media Session API, I'll definitely take a look.

You're right that both audio and image can be treated as embedded media, but this is exactly what EPUB already does, and it's part of the reason why EPUB is a terrible publication format for comics (along with very poor metadata).

When you interact with a publication, there are essentially two things:
- the publication itself
- a number of interactions available, for example turning a page, seeing the next panel in a comics, listening to the next chapter in an audiobook etc.

If you want to completely tie both the publication and these interactions together and have complete control over them, then embedding these media in HTML is great.

But if you want to separate them from one another, using an embedded media makes things trickier.

If instead of the HTML/JS containing the publication, I'd like another app (doesn't matter if it's a Web app, native app, online/offline, whatever) to handle these interactions, it's usually much easier to access the media directly than an HTML container where the media is embedded.

That's one of the reason why CBR/CBZ which is one of the most stupid and straightforward publication format you could ever imagine (bitmaps in a zip, ordered by file name) is by far the most popular format for comics. It's super easy for any app out there to just get right to the content, and add nifty features over it (intelligent zooming, image processing, detecting panels automatically, you name it).

Same idea for podcasts which have basically a manifest (RSS feed with embeds) and direct links to audio files.

Now don't get me wrong, I'm not saying that one is better than the other, but depending on the kind of comics that you're designing, you'll be either better off having full control over most things in HTML/JS, or letting the reading environment (browser, native app, another web app) decide what it would like to do.

In an ideal world, I believe that a comics should have:
- its own publication manifest pointing directly to various bitmaps, that also contains the kind of advanced metadata that you might expect from a publication
- but also a number of HTML documents, proper JS for handling interactions/cache and a web app manifest

That would truly be the best of both worlds:
- works by default in any browser out there, treated like an app on some devices, the author can provide dedicated controls
- yet at any time I can switch to another app and benefit from another set of features that makes my reading experience different

**Comment by marcoscaceres** [comment]
@HadrienGardeur, underlying your comments might be the technological limitations imposed by ePub ... which is really sad, because there should be the possibility for authors to use _all the web_, including hardware accelerated zooming and panning on comic's panels, etc. 

Really, the possibilities there should be limitless, given that the web supports WebGL (and we've been building interactive experiences on OpenGL for over a decade) and there is also hardware accelerated CSS transitions.

> the author can provide dedicated controls

There are ways to do this - but they have to be provided "in-app". Browsers don't allow developers to fiddle with the UI of the browser for reasons of security, privacy, and user experience. 

> yet at any time I can switch to another app and benefit from another set of features that makes my reading experience different

This is largely supported already. As I mentioned previously, many browsers support "reader view" out of the box - we might just need to tweak that a little bit. 

We also have various [display modes](https://www.w3.org/TR/appmanifest/#display-modes) that authors can leverage to provide the optimal experience for their works.

**Comment by HadrienGardeur** [comment]
It's not only a technological limitation, this is also a separation of concerns. 
I don't necessarily want a publication to decide entirely on its own how I will be able to interact with it, or the features that will be available.

For example, if I'm reading Proust for fun, I will have completely different expectations compared to having a class about Proust for a full semester.

If I'm simply going through a book during my summer holidays, simply turning pages, having access to a table of contents and having my last position in the book saved for me might be enough.

But if I'm writing a PhD on the same book, I probably want to have extensive annotation support, access to a specialized glossary, have discussions in the margins with other experts etc.

Modern Web technologies can definitely handle all these things for me in a neat UI, but it doesn't know in advance what I'll need.

As a reader, I should be free to read any publication in any reading environment that I prefer.

Browsers could certainly adapt their reader mode for such publications, but I should also be able to simply provide the URI to a manifest to any app that I'd like to use, and get a different reading experience from them.
This has obvious security concerns, that will have to be covered by this group, a lot of it will be similar if not the same as the work that has been done on the Web App Manifest.

I think that the focus on package and online/offline, and the earlier comments in this thread do not matter as much as this separation between the publication and its reading environment.

**Comment by lrosenthol** [comment]
On Tue, Sep 27, 2016 at 4:33 PM, Hadrien Gardeur notifications@github.com
wrote:

> It's not only a technological limitation, this is also a separation of
> concerns.
> I don't necessarily want a publication to decide entirely on its own how I
> will be able to interact with it, or the features that will be available.
> 
> On the other hand, the author of the publication may very much want to
> force you into a specific interaction model - and that needs to be
> supported as well.

But this takes us to the classic debate of "author intent" vs. "consumer
intent" that separate EPUB (which is all about consumer intent) from every
other publication format (PDF, the web, etc.) where the author's intent is
primary.

> For example, if I'm reading Proust for fun, I will have completely
> different expectations compared to having a class about Proust for a full
> semester.
> 
> If I'm simply going through a book during my summer holidays, simply
> turning pages, having access to a table of contents and having my last
> position in the book saved for me might be enough.
> 
> But if I'm writing a PhD on the same book, I probably want to have
> extensive annotation support, access to a specialized glossary, have
> discussions in the margins with other experts etc.
> 
> Modern Web technologies can definitely handle all these things for me in a
> neat UI, but it doesn't know in advance what I'll need.
> 
> All good examples.  But how many of those things are really native to the
> publication vs. things you'd like to see in your UA/RS?  To me, most those
> are all UA/RS issues.  However, I would think that TOC support could go
> either way - it might be something that the author wants integrated into
> the publication (as there is a specific experience they want to present).
> 
> Browsers could certainly adapt their reader mode for such publications,
> but I should also be able to simply provide the URI to a manifest to any
> app that I'd like to use, and get a different reading experience from them.
> 
> There is a slippery slope here that I hope we do not go down.  While I
> agree with the first part - that a user should be able to view their
> publications in any UA/RS of their choice - the primary experience for the
> publication MUST be the same across those consumption tools.  Sure - some
> may have extra features or adapt to the device - but at the end of the day,
> the user should not be surprised about the differences.

**Comment by GarthConboy** [comment]
This issue may be well served by seeing how the forthcoming version that bifurcates WP from Packaged/Portable impacts the discussion.   Tentatively reflect on our post-TPAC afterglow?  :-)

**Comment by HadrienGardeur** [comment]
> But this takes us to the classic debate of "author intent" vs. "consumer
> intent" that separate EPUB (which is all about consumer intent) from every
> other publication format (PDF, the web, etc.) where the author's intent is
> primary.

It's not as clear cut as you describe it. If I open a FXL book, or use a reading environment that does very little in terms of overriding styles, then "author intent" would also be prioritized with an EPUB.

> All good examples.  But how many of those things are really native to the
> publication vs. things you'd like to see in your UA/RS?  To me, most those
> are all UA/RS issues.  However, I would think that TOC support could go
> either way - it might be something that the author wants integrated into
> the publication (as there is a specific experience they want to present).

On the Web, absolutely all of these features could be part of the publication, you don't have this distinction that we're use to in EPUBland.

Ideally we should allow both and design a publication format that can behave like a Web app (where the author has complete control over the features) but where I can also at any time get a URI to the publication itself (or auto-discover it) and bring it in another reading environment.

Web folks believe that publications should behave exactly like Web apps, EPUB folks want complete separation between the publication and it's reading environment (what you called User Agent or Reading System). What we need to find is a middle ground, that can work for both.

> There is a slippery slope here that I hope we do not go down.  While I
> agree with the first part - that a user should be able to view their
> publications in any UA/RS of their choice - the primary experience for the
> publication MUST be the same across those consumption tools.  Sure - some
> may have extra features or adapt to the device - but at the end of the day,
> the user should not be surprised about the differences.

Are you advocating for a publication format closer from PDF than EPUB in terms of control provided to the user then?

With EPUB today, the reading environment can already provide a vastly different experience if it wants to. I'm not sure what the definition of "surprised about the differences" would be exactly, but I can be really surprised if I compare various EPUB RS today.

**Comment by HadrienGardeur** [comment]
> This issue may be well served by seeing how the forthcoming version that bifurcates WP from Packaged/Portable impacts the discussion. Tentatively reflect on our post-TPAC afterglow? :-)

I think the impact of the package on the overall design is somewhere between minimal and non-existent.

In EPUB, we overcomplicate things a whole lot with many different files and well-known locations. All that you need to package a publication is:
- a container (ZIP?)
- a well-known location/name for the manifest (manifest.json?)

That's it. No need for all the craziness that we've inherited in EPUB from previous standards.

**Comment by mac2net** [comment]
Frankly @HadrienGardeur you sound like me and this is what I've been saying to the group for almost a year. And in fact, as I have said and demonstrated with functional samples, we can also start by stuffing everything into one file and serving it up with file:///. This eliminates the necessity for a zipped container or a manifest.
It doesn't matter that File URLs are imperfect. The W3C, IETF and Whatwg will improve it if there is demand. 
And instead of discussing how theoretical technologies might work together, we could just use what's available already. Almost everything that works online in a browser, works offline in browser already. 
And these tools can be used to develop virtual solutions to the different requirements folks here think are so vital to their publications.
And through this process, some things will rise to become part of the core spec while others won't or will have to wait.

**Comment by HadrienGardeur** [comment]
> Those are one and the same thing, @hadrien. The ability to move reading
> environments has nothing to do with author intent.  I can use completely
> different browsers today to view the web - each with different levels of UX
> and additional features.  HOWEVER, the content itself always looks the way
> the author intended (including whether it reflows or not, and if so, how)

It's not one and the same thing.

Of course, any Web Publication format should work in a similar way across browsers, but if navigating the publication itself is something entirely done in JS for instance and completely tied to the publication, you won't be able to read it wherever/however you want.

When I say any reading environment, I truly mean anything:
- a browser
- a Web app
- a native app

These different reading environments should mostly render things the same way (although I could also use an accessible reader which could do things completely differently), but could provide vastly different features in terms of navigation and interacting with the publication.
To make this possible, you want to have a separate manifest for the publication containing all the useful info, and be able to separate the content of the publication from the embedded reading environment.

**Comment by HadrienGardeur** [comment]
> That is the world of EPUB.  It is not the world of the web and Web
> Publications - IMO.

Well this is where I disagree, I believe that it's perfectly possible to handle both at the same time.

**Comment by iherman** [comment]
> > > To make this possible, you want to have a separate manifest for the publication containing all the useful info, and be able to separate the content of the publication from the embedded reading environment.
> > > That is the world of EPUB.  It is not the world of the web and Web Publications - IMO.
> > > Well this is where I disagree, I believe that it's perfectly possible to handle both at the same time.

To be honest, I am lost in this discussion, and I am not even sure whether you guys really disagree.

Can someone summarize what is really what you guys mean? (Not in terms of EPUB, but in terms of Web Publications?)

Actually, this discussion has gone so far away from the original topic of the issue (which may become moot after we make a new draft of the UCR based on earlier discussions and the decision of the F2F last week) that it may be worth starting a separate issue making the, well, issues clear...

Thanks

**Comment by HadrienGardeur** [comment]
@iherman it is still related to the original message, although a bit indirectly.

Let me explain:
- in EPUB, while reading chapter 1, I have no mean of getting to chapter 2 that is directly available in the HTML/JS (a link in the body of the document for example). To continue the navigation, the Reading System has to be aware of the OPF (manifest) and its spine (reading order of the resouces).
- on the Web, it's exactly the opposite, there's always going to be a link in the body of the document, or something else such as a menu or JS that adds controls over my reading experience.

This is IMO the most important issue and discussion that we need to have.

It has a direct impact on a possible "offline mode" for the following reasons:
- if a Web Publication has strictly links in the body of its resources and nothing else, it will be very difficult to bring it offline
- if it has a manifest listing the resources, then it's very easy to either package these resources or use a ServiceWorker to cache them
- if it has its own ServiceWorker that's responsible for caching the resources of the publication, I'll be able to continue reading offline but packaging them might be tricky

Now, the place where we seem to disagree is that @lrosenthol is saying that the way of the Web is to have no control at all over the reading experience and just let the publication provide the navigation and everything else.
On the other hand, what I'm saying is that while the Web Publication can provide such controls, it can also link to a manifest that will let other apps do whatever they'd like to do, and facilitate the creation of a package if you want to.

**Comment by mac2net** [comment]
We don't need either a manifest or "service workers". 

I made a 4-part 5DOC with links via a TOC connecting 4 posts online and 4 5DOC files offline that can be opened n any browser.

Link to online chapter 1 of Autobiography of Benjamin Franklin:
http://samples.5doc.org/content/autobiography-benjamin-franklin-part-1/

Click hamburger menu to download all 4 offline files. As long as they are in the same directory the linked connections between the files work.

All we really need is an updated File URL scheme that accommodates a zipped offline container. 
Of course a manifest could be optional or, if necessary, with minimal requirements.

And of course service workers could be used later on in this or next decade when/if they achieve usefulness beyond caches and notifications.

**Comment by iherman** [comment]
@HadrienGardeur, thanks for the summary.

> - in EPUB, while reading chapter 1, I have no mean of getting to chapter 2 that is directly available in the HTML/JS (a link in the body of the document for example). To continue the navigation, the Reading System has to be aware of the OPF (manifest) and its spine (reading order of the resouces).
> - on the Web, it's exactly the opposite, there's always going to be a link in the body of the document, or something else such as a menu or JS that adds controls over my reading experience.
> 
> This is IMO the most important issue and discussion that we need to have.

There has been some back and forth on the github issues, but I believe there _is_ a consensus that a Web Publication will have some sort of a manifest (I do use this term in a very general sense; it is not _necessarily_ the same as the current Web Manifest spec). What exactly the format and the precise content will be is still up in the air, but my sense is that, functionally speaking, that manifest will include a ToC in some format. Ie, the (real!) problem of relying on embedded back and forth links among chapters is not really on the table right now.

I agree that this is one of the most important issues. But I do not think there is any disagreement among us on that point.

> It has a direct impact on a possible "offline mode" for the following reasons:\* if a Web Publication has strictly links in the body of its resources and nothing else, it will be very difficult to bring it offline\* if it has a manifest listing the resources, then it's very easy to either package these resources or use a ServiceWorker to cache them\* if it has its own ServiceWorker that's responsible for caching the resources of the publication, I'll be able to continue reading offline but packaging them might be tricky

See above: I think the first bullet item is not really considered.

Whether a WP will have "its ow ServiceWorker" or not, I am not 100% sure either. First of all, terminology-wise, it is not its own service worker, because SW is simply a functionality of the browser/UA just as, say, an HTML parser. But I would think you are talking about a Javascript application _on top_ of the SW functionality that would handle whatever has to be handled. My personal mental model is that the UA agent would have some sort of an extension (or "add-on" in Mozilla parlance) for WP management that should be generic, and should be "data-driven" by the data in a "manifest". The ideal would be to have no need for such an extension at all because everything would be handled in the browser, making a WP a first-class entity on the Web but, I am sure, there will be at the minimum a transition period when such extension will be necessary. And even if so, I could very well imagine that the browser would handle the large majority of the publications but not 100%, which would still leave the room for specialized applications/extensions. Or these cases could be handled by an extra application carried by the WP.

But why would that be a problem with packaging? If the package were to also include the Javascript application (and I do not see why not), then I do not really see the issue (of course, there may be some problems in the very details on how the application would be started up, etc, but we are talking about a higher level picture now).

> - Now, the place where we seem to disagree is that @lrosenthol is saying that the way of the Web is to have no control at all over the reading experience and just let the publication provide the navigation and everything else.
> - On the other hand, what I'm saying is that while the Web Publication can provide such controls, it can also link to a manifest that will let other apps do whatever they'd like to do, and facilitate the creation of a package if you want to.

I let @lrosenthol react on whether his opinion is really as strict as you seem to understand... but I am certainly in favour of, for example, leaving any kind of manifest open/extensible in the sense of giving the possibility for the author to add his/her additional data if that provides extra control for specialized applications (if this is what you are referring to).

**Comment by HadrienGardeur** [comment]
@iherman

> There has been some back and forth on the github issues, but I believe there is a consensus that a Web Publication will have some sort of a manifest (I do use this term in a very general sense; it is not necessarily the same as the current Web Manifest spec). What exactly the format and the precise content will be is still up in the air, but my sense is that, functionally speaking, that manifest will include a ToC in some format. Ie, the (real!) problem of relying on embedded back and forth links among chapters is not really on the table right now.

I've seen comments in other issues that seem to challenge the idea that a manifest is needed, or at least that challenge the presence of certain things in the manifest (such as the reading order).
That said, I hope you're right because I truly believe that such a manifest is necessary.

> Whether a WP will have "its ow ServiceWorker" or not, I am not 100% sure either. First of all, terminology-wise, it is not its own service worker, because SW is simply a functionality of the browser/UA just as, say, an HTML parser. But I would think you are talking about a Javascript application on top of the SW functionality that would handle whatever has to be handled.

Yes that's what I meant: a JS script that relies on the SW API to cache specific resources and decides on the behaviour when fetching resources (cache first, network first etc.)

> My personal mental model is that the UA agent would have some sort of an extension (or "add-on" in Mozilla parlance) for WP management that should be generic, and should be "data-driven" by the data in a "manifest". The ideal would be to have no need for such an extension at all because everything would be handled in the browser, making a WP a first-class entity on the Web but, I am sure, there will be at the minimum a transition period when such extension will be necessary. And even if so, I could very well imagine that the browser would handle the large majority of the publications but not 100%, which would still leave the room for specialized applications/extensions. Or these cases could be handled by an extra application carried by the WP.

That's exactly what I have in mind too.

> But why would that be a problem with packaging? If the package were to also include the Javascript application (and I do not see why not), then I do not really see the issue (of course, there may be some problems in the very details on how the application would be started up, etc, but we are talking about a higher level picture now).

To package a publication, I need to explicitly know which resources are part of it. Otherwise, whenever I encounter a link, there's no way I can know whether it's an external reference or part of the publication.

Without a manifest (or without a reading order or list of resources in the manifest), it'll be much more difficult to package a publication.

**Comment by HadrienGardeur** [comment]
> All of those things are true but not distinct.  You can (and should), as
> @iherman says, have a web publication with links **and** a manifest.  The
> combination of the two give you the best scenario since it allows the
> author to have full control over their intent while enabling packaging
> and/or updating of various resources.
> (and it's not just about links, but **any** URL used by the OWP content)

Well then I'm glad that we agree @lrosenthol !

**Comment by iherman** [comment]
> To package a publication, I need to explicitly know which resources are part of it. Otherwise, whenever I encounter a link, there's no way I can know whether it's an external reference or part of the publication.
> 
> Without a manifest (or without a reading order or list of resources in the manifest), it'll be much more difficult to package a publication.

Yes, absolutely. But I believe the need for those resources is necessary even in case of a 'simple' offline/online: you do not want to put all the Web onto your local machine:-). Ie, this is not only a matter related to packages.

Unfortunately, when we have such a large number of issues coming in within a short time, the various discussions get a bit tangled. I guess this is in the nature of things. But issues #110, #107, #124 are just a few where these issues are discussed.

(Admin comment: we are supposed to come up with a new version of the UCR document which takes into account many of the disparate issues. It may be a good idea to 'reset' at that point, and look at all this with a fresh eye, with new issues...)

**Comment by HadrienGardeur** [comment]
> Yes, absolutely. But I believe the need for those resources is necessary even in case of a 'simple' offline/online: you do not want to put all the Web onto your local machine:-). Ie, this is not only a matter related to packages.

Well, it's "better" IMO to have it for the offline use case too, but it's not necessary.

I can simply specify in my JS which resources should or should not be cached, without using an external manifest at all.

**Comment by iherman** [comment]
> I can simply specify in my JS which resources should or should not be cached, without using an external manifest at all.

There is not necessarily a "my JS", is there? If it is a generic browser extension, then the data should be somewhere...

**Comment by HadrienGardeur** [comment]
@iherman sure, but how can we be sure that there will be a generic browser extension?

**Comment by iherman** [comment]
I do not think this is a knowledge/decision we can have right now, of course, but we should work that way:-)

**Comment by lrosenthol** [comment]
I removed the section entirely from my [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe), and moved the use case (with some cleanup) under Constituent Resources.

**Comment by iherman** [comment]
(Admin)

Though the whole section is gone (making the original issue a candidate for closure) I am hesitant to do this because the discussion has gone all over the place. Would it be possible to open new issue to 'replace' this one?

**Comment by marcoscaceres** [comment]
I'm ok with closing whatever issues and restarting fresh with a new round of review. Can always reference old issues/discussions if need be.

**Comment by TzviyaSiegman** [comment]
Closing issue as the document is completely restructured. New issues can be opened.
