### ISSUE TITLE
5.2 Distribution Process

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#115]
> Req. 21: The distribution of PWPs should conform to the standard processes and expectations of commercial publishing channels.

You can't be serious. I'm sorry, I'm going to stop reading now as this document is getting into the realm of ridiculous. 

Sad. It started off good :(

**Comment by iherman** [comment]
@marcoscaceres, I think this should be discussed further...

The formulation may not be the best (well it _isn't_ the best if it triggered this reaction...). However: we have an industry out there that has its own workflow, starting with non-technical steps like talking to editors, through the steps that involves mutual discussions and annotation of the content until the point when the content is created and published. PWP should not fundamentally upset that. There is also some forms of a businesses going on (not only trade publishers, but also journal and magazine publishers) that have business processes. We should try to reduce the (_unavoidable_) disruptions as much as we can, otherwise what we do will be ignored by the publishing industry altogether (and if so, why would we do that in the first place?). This is what this requirements tried to express...

I do not have the answers of how to do this exactly; but this is just a UCR document. What and how can be properly achieved is open.

**Comment by marcoscaceres** [comment]
Ok, it would be less offensive if it said:

> Req. 21: The distribution of PWPs should respect the existing processes and expectations of  publishing channels.

**Comment by marcoscaceres** [comment]
> The formulation may not be the best (well it isn't the best if it triggered this reaction...). However: we have an industry out there that has its own workflow, starting with non-technical steps like talking to editors, through the steps that involves mutual discussions and annotation of the content until the point when the content is created and published. 

I'd like to note that this industry is in no way special. All industries have their own set of established practices, and those practices are constantly being disrupted and adapting to change. I.e., there is a lot of give and take here. 

> PWP should not fundamentally upset that.

Sure - but the web around it might (as it's already done). 

> There is also some forms of a businesses going on (not only trade publishers, but also journal and magazine publishers) that have business processes. We should try to reduce the (unavoidable) disruptions as much as we can, otherwise what we do will be ignored by the publishing industry altogether (and if so, why would we do that in the first place?). This is what this requirements tried to express...

The requirement needs clarification because this hits serious "innovators dilemma" issues - and as currently reads, it sounds like protectionist collusion from the publishing industry. That might not be the intention, but that's how it currently reads.

**Comment by iherman** [comment]
Proposed solution: reformulate per [Marcos' comment](https://github.com/w3c/dpub-pwp-ucr/issues/115#issuecomment-246909084)

**Comment by sideshowbarker** [comment]
> as currently reads, it sounds like protectionist collusion from the publishing industry. That might not be the intention, but that's how it currently reads.

I think a lot of people reading this document are going to see that language that way as well.

It’s certainly not a requirement that follows from actual user needs. Instead it seems to be stating a requirement—or even a restriction—that others might want to put **on** users based on their needs.

I realize there are associated use cases listed in this section but I think the problem a number of those have is the same general problem this entire document has—an assumption that some sort of new packaging format is required, while at the same time making no assumption that existing-standard Service Workers are available.

> I'd like to note that this industry is in no way special. All industries have their own set of established practices, and those practices are constantly being disrupted and adapting to change. I.e., there is a lot of give and take here.

Right. And we need to be developing a technology here to serve a lot more than just “commercial publishing channels“ and not just be favoring any one industry in the language in our documents.

In comparison, in developing HTML5 video, I do not recall that we ever produced any documents explicitly stating anything about it had to serve the needs of the “streaming broadcast channels” or anything like that. We didn’t have to, because we were building a solution to meet user needs first, and the solution itself clearly had broad applicability in all kinds of contexts.

**Comment by marcoscaceres** [comment]
> In comparison, in developing HTML5 video, I do not recall that we never produced any documents explicitly stating anything about it had to serve the needs of the “streaming broadcast channels” or anything like that. We didn’t have to, because we were building a solution to meet user needs first, and the solution itself clearly had broad applicability in all kinds of contexts.

This. So. Much. This. 

Ok, I've had my hissy-fit and will go back to reading the document now :)

**Comment by GarthConboy** [comment]
A discussion of "user" is on the TPAC DPUB IG agenda.   Current usage is more than Reader, extending to Publisher, Author, Implementor, perhaps -- regardless a viable point of discussion/clarification.

**Comment by iherman** [comment]
The editorial change per [Marcos' comment](https://github.com/w3c/dpub-pwp-ucr/issues/115#issuecomment-246909084), has been done in the [separate editorial branch](https://github.com/w3c/dpub-pwp-ucr/blob/pwp-ucr-editorial1/index.html).

The issue has been left open, because it was discussed further (although the issue may become moot due to the discussions elsewhere).

**Comment by lrosenthol** [comment]
I also made a bunch of changes to this in my [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe) to address distribution in a variety of ways.

**Comment by iherman** [comment]
The formulation of Marcos is now in the document, closing this.
