### ISSUE TITLE
Usage (or not) of the term "reading system"

### ISSUE THREAD

**Issue by iherman** [w3c/dpub-pwp-ucr#117]
This a branch from issue #107, raised by @marcoscaceres (in a [comment](https://github.com/w3c/dpub-pwp-ucr/issues/107#issuecomment-246892323)):

> The whole notion of a "reading system" should be discarded, IMO in favor of "user agent" or "browser"

**Comment by iherman** [comment]
For better or for worse, the term 'reading system' has been used by the publisher community so far for any sort of digital publication reader, whether software or hardware. This is indeed a different terminology than the one used by the web developers' community, but we cannot ignore it.

Proposal: add, into the terminology section, a separate entry to explain where this term comes from.

**Comment by marcoscaceres** [comment]
Ok, but be cautious to not confuse it with, and kindly differentiate it from, user agent.

**Comment by iherman** [comment]
Well... in fact, on long term, there should be no major difference and I would be (personally) in favour of dropping the term altogether. On shorter term a 'reading system' is probably a traditional user agent with some sort of an extension... and I would think that, in this document, this is what the term should really mean (which actually re-emphasizing that an entry in the terminology section would be necessary).

**Comment by sideshowbarker** [comment]
> “reading system” is indeed a different terminology than the one used by the web developers' community, but we cannot ignore it.

Why?

> Well... in fact, on long term, there should be no major difference and I would be (personally) in favour of dropping the term altogether.

I agree that the term “reading systems” should be dropped and I believe we have sufficient evidence already to indicate that some others would agree.

Given that, I counter-propose that instead of adding anything to the Terminology section to explain what “reading system” means, the editors should instead actually completely drop the term from this document (and from any other documents the group publishes in TR space) and just use the term “user agent”, as our other TR documents for Web-runtime technologies consistently do.

We publish documents in TR space for use in the long term, not in the short term. So short-term concerns should not be taken into consideration for TR docs. The short term can instead be addressed in wikis and such.

Anyway, as far as the relevance of the “reading system” term itself: Many technologies that we’ve developed for the Web have had some relationship to legacy off-Web runtimes/systems, but in those cases we did not need to elevate the legacy terminology to use as the name of what we were creating. For example, the Web was not defined using terminology from Gopher, we did not ever attempt to define HTML5 video in terms of interaction with the Flash runtime (which is what users were forced to use for seeing video on the Web before we created HTML5 video and eventually nearly completely displaced use of Flash for video).

So just because many users in practice are currently forced to use off-Web “reading systems” to read certain kind of publications, it does not follow that we have to give the legacy “reading systems” name to any new thing we are developing—especially if the effect in practice is that we are going to displace the use such systems (obviate user need for them).

**Comment by TzviyaSiegman** [comment]
I'd be OK with replacing "reading system" with "user agent" because it is a subcategory.

**Comment by lrosenthol** [comment]
The one reason that I would be concerned with using user agent is that a consumer of a PWP may be more than just a standard OWP UA - it may want/need to do more things (not known yet) and so it may confuse people if we call it a UA but it's not the same as an HTML UA...

**Comment by GarthConboy** [comment]
+1 to Leonard's comment.

Reading System does, for better or worse, come from EPUB-land.  In that world a packaged publication may go through various phases (ingest, serving, rendering) that _may_ happen in disparate computing environments.  Reading System covers the end-to-end process.

Any packaged manifestation of a PWP would like still want a term to cover the holistic system, so perhaps better to retain for now.

**Comment by TzviyaSiegman** [comment]
I disagree with @lrosenthol. Whatever happens (ingest, chew, spit out, process, render), the reading system is still a user agent. UA is a vague term with no strings attached. A reading system is a kind of user agent. The human reader still interacts with it as a user agent.

**Comment by lrosenthol** [comment]
@TzviyaSiegman then what would you call a "thing that doesn't interact with the user"?  For example, in other standards we call it a '_processor_'.  Now I am not suggesting that we adopt that term as it's not one used in the web world - but raising the point that (as @GarthConboy) said, they are **not** the same things.

**Comment by GarthConboy** [comment]
A little unclear that the current [User Agent Definition](https://www.w3.org/WAI/UA/work/wiki/Definition_of_User_Agent) can cover the full line of processing from ingest to serve to render.  But, I'll clearly agree with the @TzviyaSiegman statement of "The human reader still interacts with it as a user agent."

This may all be a pedantic point best discussed over a glass of port!

**Comment by marcoscaceres** [comment]
The "ingest, chew, spit out, process, render" is defined by HTML and its various underlying specs (fetch, dom, etc.). Those all rely on the concept of a user agent. There is nothing special, AFAICT, about a PWP or an application that would render a PWP. Any new features/APIs resulting from the PWP effort would benefit the web as a whole, hence would be part of the standard web platform (and by definition, user agents).

... drops the 🎤.

**Comment by iherman** [comment]
At this point, I am more in favour of going for a clean cut and drop the term reading system in this document. I do not think that, on long term, it makes sense to keep a separate term in a brave new world of PWP...

(We can add a note in the terminology section of the document that this is the term we use and that is roughly equivalent to what the publication industry calls reading system.)

**Comment by GarthConboy** [comment]
I will not hold my breath and turn blue!  :-)   And like Ivan's proposed note.
