### ISSUE TITLE
5.5 External Data needs to be "unpackaged"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#121]
5.5 External Data is heavily biased towards a packaged thing. Please rewrite this section to be package neutral.

**Comment by iherman** [comment]
@marcoscaceres we decided to have a thorough reorganization of the UCR document, including a structure that would reflect the discussions, our writeups, etc. Due to timing, editors' other obligations, etc, this will take 1-2 weeks. We will have to look at these at that point again, including reformulation, but that explains why things are up in the air for a while (afaik, the work will be done in a separate branch first, ie, not visible on the gh-pages one)

**Comment by marcoscaceres** [comment]
That's fine, I'm tracking the repo. 

I'm really hopeful that what will emerge after all these discussions is a document that is only a couple of pages long (ideally no more than 4! Hopefully just 1 page). There are good requirements in the document, but there is way too much redundant content there.

**Comment by iherman** [comment]
Our current plans is to
1. Reorganize the overall structure to 2-3 top level sections (Web Publications, Packaging, maybe some common things, not sure about the third)
2. Trim, ie, remove duplications, etc. I am doubtful about the 4 pages (hm, do we use a print oriented term here? Wow!) but let us see that for later...

**Comment by marcoscaceres** [comment]
> Trim, ie, remove duplications, etc. I am doubtful about the 4 pages (hm, do we use a print oriented term here? Wow!) but let us see that for later...

I print all the specs. I hate reading from screen :)

![screenshot 2016-09-28 15 14 28](https://cloud.githubusercontent.com/assets/870154/18901439/4a3308ec-858e-11e6-98b7-cb60d70f2791.png)

**Comment by lrosenthol** [comment]
Completely revamped this section to include both packed and online (and both!) examples, whiel renaming the title to "Data".

**Comment by iherman** [comment]
Closing the issue; the latest version #157 has been thoroughly reorganized, it is not really possible to track this issue. A new set of review may open new issues, of course...
