### ISSUE TITLE
6.7 Combining Manifests

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#129]
Please just drop this. If authors want to do this insanity, they can... but the requirement is vague at best and deeply misguided at worst.

**Comment by iherman** [comment]
> On 28 Sep 2016, at 04:41, Marcos Cáceres notifications@github.com wrote:
> 
> Please just drop this. If authors want to do this insanity, they can... but the requirement is vague at best and deeply misguided at worst.

I do not know whether I agree with your characterization as 'insanity' or 'misguided'. I believe it is a valid use case in general, except that it may lead to serious complications to implement it. Which is a different statement (which I agree with!), and this is probably a use case that _cannot_ be fulfilled. (Hence the warning note.)

I am not fighting for not removing it but, in some sense, this means we make a decision due to implementation issues. I am not sure that is the right way to do it.

**Comment by lrosenthol** [comment]
The reason that we introduced this complex concept was that we are unaware
of a web-savvy way to approach the problem.  Maybe you can help us with it,
@marcos.

Putting this is pure web terms...

I have a web page (hosted on some provider that I don't control) where I
maintain the official copy of some important document (let's call it FOO).
Whenever anyone visits that page (aka resolves the URL), I want them to not
only get FOO itself but also any comments that people have left about FOO.
Unfortunately, my hosting provider doesn't allow commenting.  We believed
that having a model whereby various related pieces (eg. FOO, FOO comments,
etc.) could be "integrated on the fly without requiring changes to FOO or
its hosting environment) would address this.

how would you suggest this scenario be handled??

**Comment by dauwhe** [comment]
@iherman, I wonder if there are in fact lots of different use cases here, which all boil down to adding or subtracting what's included in the P?WP, and editing parts of the P?WP itself.
1. Editing metadata of a WP. This is part of the scenario in the use case doc, I think.
2. Associating annotations with an existing WP, as mentioned by @lrosenthol above. More on this use case in a separate comment.
3. Creating a new WP by combining existing WPs. This might be different than
4. Creating a new entity that is a collection of WPs.
5. Creating an alternative "view" of a WP, with different ordering of components (mentioned in the doc, and too close to multiple renditions to make me happy).

What these all have in common is changing a WP. Are there requirements here that go beyond the web's idea of authoring?

**Comment by iherman** [comment]
@dauwhe I believe we are talking exclusively of "changes" of  PWP without any change on the content itself. Providing an alternative reading order, for example, for some users, does not change the content, just the data described in the "manifest" (in quotes:-). Similarly, a library may want to change (or probably add) library specific data to be used by reading systems, like a different identifier, dates of the loan, that sort of things.

In theory, all those cases can be handled by providing an _alternative_ manifest instance, ie, without changing the original one, and making it sure that the user agent takes _that_ manifest and not the one that I cannot change. That is why I believe the possibility of providing the reference to a manifest via the HTTP LINK header is important.

This use case is more of a convenience. Instead of redoing the full manifest, incorporating my changes, I could do only my deltas, and let the system combine them.  

There is a more general situation of how to edit WP-s, but that is indeed the same as the Web's idea of authoring. But I do not think we should go there.

**Comment by GarthConboy** [comment]
Given the @marcoscaceres original issue and the reply from @iherman of "and this is probably a use case that _cannot_ be fulfilled" and our desire to trim the UCR document... I think I'd get on the "remove" bandwagon -- we have to leave some windmills for future generations to tilt at!

**Comment by HadrienGardeur** [comment]
I'm also in favour of dropping this requirement, which seems impossible to fulfill anyway.
