### ISSUE TITLE
7. Locators is redudant

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/dpub-pwp-ucr#130]
Locators are just URLs dressed up as something fancy ("state-independent locator" 0_o). 

Yes, we need to reference bits inside publications: but please don't try to dress this up as something fancy with RFC6596 and fancy terminology. 

The requirement is just that people need to link externally to, and relative to, the resource. That's it. And it's a given, it's a freeken website after all - don't go crazy. 

I suggest just dropping this whole section. 

Also, please stop dreaming of a world where the web has stable URLs. That doesn't exist. The Web is volatile, links break, etc. That's a feature, not a bug - and definitely not something this group or any group can fix. 

Expect things to break. Expect annotations to break - and expect different solutions to come about to overcome those issues. Those issues may be solved via URLs or they may be solved using something completely different (e.g., using git-style diffing and hashes to work out where annotations go after an update).

**Comment by iherman** [comment]
> On 28 Sep 2016, at 04:52, Marcos Cáceres notifications@github.com wrote:
> 
> Locators are just URLs dressed up as something fancy ("state-independent locator" 0_o).
> 
> Yes, we need to reference bits inside publications: but please don't try to dress this up as something fancy with RFC6596 and fancy terminology.
> 
> The requirement is just that people need to link externally to, and relative to, the resource. That's it. And it's a given, it's a freeken website after all - don't go crazy.
> 
> I suggest just dropping this whole section.
> 
> Also, please stop dreaming of a world where the web has stable URLs. That doesn't exist. The Web is volatile, links break, etc. That's a feature, not a bug - and definitely not something this group or any group can fix.
> 
> Expect things to break. Expect annotations to break - and expect different solutions to come about to overcome those issues. Those issues may be solved via URLs or they may be solved using something completely different (e.g., using git-style diffing and hashes to work out where annotations go after an update).

If we also consider the issue of Packaged Web Publications, even if some sort of a layer on top of pure Web solutions, then this the situation becomes more complex. Remember that in the publication world a unique identification of a 'work' (as opposed to a specific manifestation) is essential, as it has already discussed elsewhere.

It is true that this set of requirements become an issue related to the Packaging part only, so we may want to postpone this until after the reorganization of the document. But it should not be forgotten.

As for the stable URLs: again, we should not dismiss this issue lightly. This is not just a freeken website when it comes, e.g., to a scientific article; you want to be 100% sure that the article is available, and all references thereof, at a stable space in several decades. That is how DOI-s come into the picture because URL-s have failed to provide that stability…

But this comes back to the whole issue of identifiers. Separate (and long) discussion...

**Comment by lrosenthol** [comment]
I agree that we should separate the "embedded resource" problem from the
"stable URL" problem.  Having them together may make it
difficult/impossible to resolve.

But both are quite important, as mentioned by Ivan, etc.

I'll see about splitting up these requirements.

**Comment by lrosenthol** [comment]
I tried to address this in the Manifests and Links section of the updated document.
