### ISSUE TITLE
Slicendice Publishing: Distribution and Versioning usage example

### ISSUE THREAD

**Issue by dauwhe** [w3c/dpub-pwp-ucr#146]
The document says:

> Slicendice Publishing publishes many PWPs, some of which are different versions or subsets or combinations of others. Slicendice needs not only to be able to uniquely identify each unique PWP but also to identify each "copy" or "delivery" ("item") of each of those PWPs so that it can track "what" has been sold and "how many" of each one have been sold.

Several things:
1. In general, we might avoid some potential confusion by adopting FRBR terminology. A PWP in general is a manifestation of an expression of some work. We know we want to uniquely identify a manifestation. The question here almost seems to be about uniquely identifying an item??
2. The general question of versioning is hard. My first instinct would be to delete the idea of versions from this use case. 
3. The remaining use case is around publishing different subsets or combinations of PWPs. We know that each subset or combination will need an identifier. But is this use case saying each item needs to be "identified" individually? I don't understand. I can count how many copies of Moby-Dick I sell without a serial number on each book. MassiveTechCo is able to send SemiGiantTradePublisher sales reports about EPUB, in spite of EPUB not having any sort of unique item identifier. Is this really a requirement for the format?

I think there might be a slidendice use case around metadata, indicating that a PWP, while being its own thing, is also a part of a larger work, or is constructed from other works. But I don't see a requirement around identifiers.

**Comment by BillKasdorf** [comment]
This was the one I pointed out on the call is really more than one use case. I had said two, but it's more than two.

I would advocate slimming these down so that they only involve one use case and requirement. I have come to think that use cases that involve multiple issues serve more to muddy the issues than clarify them. I think that addressing multiple issues is appropriate only if _that combination_ of issues is itself a unique use case that isn't otherwise addressed by the separate individual use cases. The individual use cases should almost always be sufficient.

So one use case is the slicendice case, using components from one or more publications to make a new publication. Fundamentally that really isn't a new use case because those components are just "resources" used to create a publication, which our fundamental definition covers. The slippery part is that some of those components can themselves be publications. My current thinking is: so what? If I publish magazine article A as a publication (with all its constituent images, maybe a stylesheet, maybe a video, maybe an interactive doohickey, whatever else) then that's a PWP; and then I also use that article as a component of another publication (maybe changing it, maybe not), then that's another PWP. Sure, I'd want to know that that part of the second PWP is actually the first PWP, but that's just metadata, which we already have covered, right? All I see that's relevant here is that I need to be able to associate metadata with a component of a PWP, not just the entire PWP.

One use case implied by the current text is the need to identify the publication and separately each of its copies. I had suggested saying "track" sales of copies rather than implying that each copy needs an identifier. So really this is just the publication needing a unique identifier, which we already have; that's the canonical identifier.

And another use case implied by this one is the versioning use case. We've already discussed that separately too.

**Comment by iherman** [comment]
> On 10 Oct 2016, at 22:19, BillKasdorf notifications@github.com wrote:
> 
> This was the one I pointed out on the call is really more than one use case. I had said two, but it's more than two. 
> 
> I would advocate slimming these down so that they only involve one use case and requirement. I have come to think that use cases that involve multiple issues serve more to muddy the issues than clarify them. I think that addressing multiple issues is appropriate only if _that combination_ of issues is itself a unique use case that isn't otherwise addressed by the separate individual use cases. The individual use cases should almost always be sufficient. 
> 
> So one use case is the slicendice case, using components from one or more publications to make a new publication. Fundamentally that really isn't a new use case because those components are just "resources" used to create a publication, which our fundamental definition covers. The slippery part is that some of those components can themselves be publications. My current thinking is: so what? If I publish magazine article A as a publication (with all its constituent images, maybe a stylesheet, maybe a video, maybe an interactive doohickey, whatever else) then that's a PWP; and then I also use that article as a component of another publication (maybe changing it, maybe not), then that's another PWP. Sure, I'd want to know that that part of the second PWP is actually the first PWP, but that's just metadata, which we already have covered, right? All I see that's relevant here is that I need to be able to associate metadata with a component of a PWP, not just the entire PWP. 

+1. Didn't we agree on the call that we would remove the whole section as not _really_ a use case for (P)WP?

> One use case implied by the current text is the need to identify the publication and separately each of its copies. I had suggested saying "track" sales of copies rather than implying that each copy needs an identifier. So really this is just the publication needing a unique identifier, which we already have; that's the canonical identifier. 
> 
> And another use case implied by this one is the versioning use case. We've already discussed that separately too.

**Comment by TzviyaSiegman** [comment]
@iherman Yes, that was consensus on the call. I think @lrosenthol agreed to remove.

**Comment by lrosenthol** [comment]
and I did remove it before sending to heather, IIRC
