### ISSUE TITLE
dpub-loc identified use cases

### ISSUE THREAD

**Issue by bjdmeest** [w3c/dpub-pwp-ucr#19]
## Configurability of important resources

Chef Bob writes a cookbook with a lot of embedded videos to explain certain techniques.
Bob finds it very important that his videos remain available even offline, and configures this in his cookbook.
Reader Annie starts reading Bob's cookbook online.
When Annie gets disconnected, the fonts of the cookbook fall back to the system fonts, but the videos remain available.

Typographer Charlie writes a book on typography, and configures differently: he finds fonts a very important aspect of his book,
whilst the embedded videos may fall back to a still.
Annie can read Charlie's book without err, online or offline. The fonts remain availabe, but the videos fall back to stills when offline.

Author David does not configure anything to his novel, but still,
Annie can read David's book without problems whether she is online or not.
## Cross-references

Writer Annie writes a dissertation. She references to her Master's thesis, published
on the university website.
Her college Bob already read her Master's thesis before. When he clicks the reference
in Annie's dissertation, he gets redirected to his local copy of Annie's Master's thesis.
Her friend, Charlie, hasn't read her Master's thesis before. Charlie needs to be online when clicking
the reference, to read Annie's Master's thesis.
## Distribution

Publisher Corp.Inc. publishes a new PWP, and sends this PWP to ACME and many more retailers.
Retailer ACME makes this PWP book available to its customers.
This PWP is downloaded to devices, or synced across several devices, or made available to a customer-specific cloud.
Customers can access this file from different retailers, through different applications, either directly or downloaded from private cloud.
Thus, the PWP is duplicated many, many, many, many, many times, resulting in a huge number of items.
There is one source manifestation, one isbn identifier, and lots of items spread across devices and buyers.

Annie buys a book and dowloads it offline. She bookmarks a certain chapter (i.e., creates a locator for that chapter).
She sends that bookmark to Bob.
Bob is able to use that locator on any item of the same PWP, and gets redirected to the correct chapter.

Q1: Is it the packaged state that goes to the retailer?
Q2: Is it up to the retailer to maintain portability?
## Offline publications

Corp.Inc. creates an internal manual for its employees as a PWP.
This PWP is not published online, but is sent around to all its employees.
Employee Anna has some questions about figure 2b, and sends an email to co-worker Bob with a locator to that figure.
Bob clicks on that locator, and his company-branded PWP reader opens Bob's personal copy of the manul, and redirects immediatly to that figure.
## Updating PWP's

Corp.Inc. creates a PWP with dynamically updatable stock exchange information on chapter 4.
Anna sends the locator for chapter 4 to Bob on April 1st.
When Bob reads the PWP offline, chapter 4 is filled with some default content.
However, when Bob gets online and clicks on the locator for chapter 4, he gets the updated stock exchange information,
which might be different than the stock exchange information that Anna saw when she created the bookmark.
## Minimal requirements

Anna is a self-publishing author.
Anna creates a PWP, both packed and unpacked.
Anna uses some cloud storage system such as DropBox to publish her PWP online.
Her friend Bob is able to read Anna's PWP online and offline, either packed or unpacked, as Bob sees fit.

**Comment by iherman** [comment]
I try to add some explicit requirement to each use case. At some point, these types of requirements will have to be reconciled for the final UCR document I guess...

> ## Configurability of important resources
> 
> Chef Bob writes a cookbook with a lot of embedded videos to explain certain techniques.
> Bob finds it very important that his videos remain available even offline, and configures this in his cookbook.
> Reader Annie starts reading Bob's cookbook online.
> When Annie gets disconnected, the fonts of the cookbook fall back to the system fonts, but the videos remain available.
> 
> Typographer Charlie writes a book on typography, and configures differently: he finds fonts a very important aspect of his book,
> whilst the embedded videos may fall back to a still.
> Annie can read Charlie's book without err, online or offline. The fonts remain availabe, but the videos fall back to stills when offline.
> 
> Author David does not configure anything to his novel, but still,
> Annie can read David's book without problems whether she is online or not.

**Requirement**:
- it SHOULD be possible to describe explicitly which resource _does_ and which _does not_ belong to the PWP or, to the “portable” part of a PWP.

---

> ## Cross-references
> 
> Writer Annie writes a dissertation. She references to her Master's thesis, published
> on the university website.
> Her college Bob already read her Master's thesis before. When he clicks the reference
> in Annie's dissertation, he gets redirected to his local copy of Annie's Master's thesis.
> Her friend, Charlie, hasn't read her Master's thesis before. Charlie needs to be online when clicking
> the reference, to read Annie's Master's thesis.

**Requirements**:
- There MUST be a separation between a format-independent (“canonical”) and format-dependent locator
- It MUST be possible (and necessary) to use, for all cross-references, the canonical locator

---

> ## Distribution
> 
> Publisher Corp.Inc. publishes a new PWP, and sends this PWP to ACME and many more retailers.
> Retailer ACME makes this PWP book available to its customers.
> This PWP is downloaded to devices, or synced across several devices, or made available to a customer-specific cloud.
> Customers can access this file from different retailers, through different applications, either directly or downloaded from private cloud.
> Thus, the PWP is duplicated many, many, many, many, many times, resulting in a huge number of items.
> There is one source manifestation, one isbn identifier, and lots of items spread across devices and buyers.

**Requirements**:
- There MUST be a separation between the _identifier_ (eg, isbn) and the (canonical) locator of a specific instance of a PWP.
- There SHOULD be a possibility in the PWP to follow (if necessary) the copying (provenance) chain
- The Identifier (eg, ISBN) MAY serve as a canonical locator for a specific instance of a PWP

---

> Annie buys a book and dowloads it offline. She bookmarks a certain chapter (i.e., creates a locator for that chapter).
> She sends that bookmark to Bob.
> Bob is able to use that locator on any item of the same PWP, and gets redirected to the correct chapter.
> - Q1: Is it the packaged state that goes to the retailer?

(I believe that is not defined)

> - Q2: Is it up to the retailer to maintain portability?

(Not sure I understand the question...)


**Requirements**
- It SHOULD be possible to use, in all circumstances, a _relative_ locator to manipulate, annotate, etc, content in a PWP
- A PWP Processor MUST be able to combine a relative locator with the canonical as well as state dependent locators of a PWP

---

> ## Offline publications
> 
> Corp.Inc. creates an internal manual for its employees as a PWP.
> This PWP is not published online, but is sent around to all its employees.
> Employee Anna has some questions about figure 2b, and sends an email to co-worker Bob with a locator to that figure.
> Bob clicks on that locator, and his company-branded PWP reader opens Bob's personal copy of the manual, and redirects immediately to that figure.

**Requirements**
- It SHOULD be possible to use, in all circumstances, a _relative_ locator to manipulate, annotate, etc, content in a PWP
- A PWP Processor MUST be able to combine a relative locator with the canonical as well as state dependent locators of a PWP

(I am not sure there are different requirements for this one, compared to the previous one. @bjdmeest, what do you think?)

---

> ## Updating PWP's
> 
> Corp.Inc. creates a PWP with dynamically updatable stock exchange information on chapter 4.
> Anna sends the locator for chapter 4 to Bob on April 1st.
> When Bob reads the PWP offline, chapter 4 is filled with some default content.
> However, when Bob gets online and clicks on the locator for chapter 4, he gets the updated stock exchange information,
> which might be different than the stock exchange information that Anna saw when she created the bookmark.

**Requirements**
- It SHOULD be possible to use, in all circumstances, a _relative_ locator to manipulate, annotate, etc, content in a PWP
- A PWP Processor MUST be able to combine a relative locator with the canonical as well as state dependent locators of a PWP
- There SHOULD be a mechanism to locate dynamic (and not only static) resources within a PWP, and use those locators the same way as for static locators.

(I am not sure there are the last requirement is with mentioning, it sounds obvious. Otherwise, are there any new requirements? @bjdmeest ?)

---

> ## Minimal requirements
> 
> Anna is a self-publishing author.
> Anna creates a PWP, both packed and unpacked.
> Anna uses some cloud storage system such as DropBox to publish her PWP online.
> Her friend Bob is able to read Anna's PWP online and offline, either packed or unpacked, as Bob sees fit.

**Requirements**:
- Any set up and mechanism, handling canonical and state-dependent locators, MUST be easily settable on any server (albeit maybe not in the most efficient manner) based on basic server behavior control.

---

**Comment by bjdmeest** [comment]
2016-04-04 10:42 GMT+02:00 Ivan Herman notifications@github.com:

**Comment by hlflanagan** [comment]
I think we've got all these in various places in the first public working draft. Please reopen if you see anything missing.
