### ISSUE TITLE
Security with scripting

### ISSUE THREAD

**Issue by TzviyaSiegman** [w3c/dpub-pwp-ucr#21]
adapted from discussion with Baldur Bjarnason and his article https://www.baldurbjarnason.com/notes/some-notes-on-security/

As a systems developer, I am concerned about allowing content that will construct a PWP to pass to my customers via my website (sales portal, server, etc) if it contains scripts from multiple and/or unknown origins.

**Comment by baldurbjarnason** [comment]
An added complications I didn't mention in the linked article (I did say simplified in the title 😊):

_Portable documents are likely to outlive the external resources they reference._

This means that a reading system for portable publications can't trust that the external scripts and styles the publication links to are actually what the document author intended to link to. The domain name could have expired and taken over by someone else in the meantime, for example.

(Yes, this is also a problem for EPUB3 remote resources. Which is why, AFAICT one of the reasons why they limited the use of remote resources to media/images.)

I don't know if this is a separate issue to this one (if it is, I can make a new issue with this comment) or not but, even though it is related to this one, it can be solved separately by requiring that reading systems support the [subresource integrity spec](https://w3c.github.io/webappsec-subresource-integrity/).

This does not solve the issue of trusting scripts of unknown origin. I have suggestions for that in a separate comment.

**Comment by baldurbjarnason** [comment]
The big problem with javascript in portable publications is that it leaves reading systems with few options for discerning whether the code it carries is malware or not.

Browsers solve this by having a unique identifier for all resources (URLs) coupled with a blacklist of known bad URLs. That and a general push towards HTTPS to prevent man-in-the-middle attacks. This is a suboptimal solution for users since it leaves them exposed to bad sites that aren't in the blacklist yet, or even to known good sites who embed bad resources via ads (which happens _regularly_ with media sites, for example).

Reading systems for portable publications could reimplement this solution by forbidding all resources that don't have a URL as an origin (no inline code, no resource loading via blob/data urls, no embedded code in any way) and requiring the publication to list the resources it intends to load beforehand.

This could be done by requiring publications to come with a Content Security Policy and disabling the publication's ability to use the 'unsafe-inline' and 'unsafe-eval' policies as well as the 'data:', 'mediastream:', 'blob:', or 'filesystem:' URL values. (This comes under 'limiting the context where JS can be run' option in my article linked to above.)

This would let the reading system use the same method as browsers do for assessing the safety of the various resources (whitelists and blacklists of known URLs) while using pre-existing specs to define the intended behaviour.

Coupled with subresource integrity (possibly requiring HTTPS as a fallback) this would pretty much solve the problem from the perspective of most reading systems since they could just piggyback off the browser ecosystem, use their lists and heuristics: the same rules and dynamics apply. It seems like a solution that is good enough and with known flaws.

This does not solve this problem for the integration, use, or embedding of Portable Web Publications in the context of _other_ websites but that's probably a separate problem. In any case I'm addressing that as a separate issue with reference to Rebus's use case for portable publications.

(If you're in the mood for spoilers, my proposed solution to that problem is to let the external context that is using/embedding the publication limit external resources to a whitelist.)

**Comment by hlflanagan** [comment]
See http://w3c.github.io/dpub-pwp-ucr/#security
If we need to flesh that out further, please reopen this issue.
