### ISSUE TITLE
Player interface

### ISSUE THREAD

**Issue by francofaa** [w3c/dpub-pwp-ucr#214]
Raising question on whether [Player interface requirement](https://w3c.github.io/dpub-pwp-ucr/#r_player), [skip by increment](https://w3c.github.io/dpub-pwp-ucr/#r_skip-by-increment) duplicates what is already available on HTML5. 

Presumably the player interface should also apply in cases where an index.html page would not be required to hold the player. Is this accurate? Should that be included in the description of the requirement? For synchronized text and media, should a different type of player be described in this requirement? 

@marisademeglio , @wareid

**Comment by wareid** [comment]
I don't think we're duplicating HTML5 here as the requirements are slightly different, but HTML5 does cover some of them. 

Yes, the player may potentially not be in the index.html, though I suspect if the player is a polyfill then probably always, and if a native player is present the index.html would be ignored entirely.

For sync text and media, I would suspect if the user chooses to see the text, the page would present as primarily text, potentially with highlighting, and the player would maybe be relegated to a footer or sidebar (since the controls aren't as important as the text).
