### ISSUE TITLE
Resource mixing and CSS counters across HTML pages

### ISSUE THREAD

**Issue by francofaa** [w3c/dpub-pwp-ucr#215]
[Layout requirement](https://w3c.github.io/dpub-pwp-ucr/#r_separate-const-resources) contradicts [example](https://w3c.github.io/dpub-pwp-ucr/#uc_separate-const-resources_css_counter) given. 

> For the purposes of layout, each resource of a Web Publication is treated as a separate document. User agents must not mix content from multiple resources in the same rendering (e.g., CSS floats or absolutely positioned elements from one resource cannot intrude or overlap with content from an other resource).

> Maeve is authoring an internal work document for her company as a Web Publication. This Web Publication spans several resources / documents, and she would like to use decimal-dot notation to indicate the section numbers. The CSS counter should be able to accumulate across the multiple resources to provide an accurate count.

Setting aside the contradiction, does the requirement that resources be treated separately from each other need to be included as a requirement since this is already how the web works? 

Is the use case presented necessary since this is not currently possible in CSS? Should this be included? If this is introduced into CSS later, would be it be safe to assume that the capability of tracking list item, section, and page number across HTML pages would also be available in Web Publications (and even EPUB)?

**Comment by laudrain** [comment]
@francofaa I don't see a contradiction between laying out a resource in a single rendering and accumulating CSS counters across multiple resources.
But this text may perhaps be improved like this in the example:

> Maeve is authoring an internal work document for her company as a Web Publication. This Web Publication spans several resources / documents, and she would like to use decimal-dot notation to indicate the section numbers. The CSS counter should be able to accumulate across the multiple resources to provide an accurate count **when layout in each separate resource**.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-06-10-pwg#section4-2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Resource mixing and CSS counters across HTML pages<br/>
Wendy Reid: <a href="https://github.com/w3c/dpub-pwp-ucr/issues/215">https://github.com/w3c/dpub-pwp-ucr/issues/215</a><br/>
For the purposes of layout, each resource of a Web Publication is treated as a separate document. User agents must not mix content from multiple resources in the same rendering (e.g., CSS floats or absolutely positioned elements from one resource cannot intrude or overlap with content from an other resource).<br/>
Maeve is authoring an internal work document for her company as a Web Publication. This Web Publication spans several resources / documents, and she would like to use decimal-dot notation to indicate the section numbers. The CSS counter should be able to accumulate across the multiple resources to provide an accurate count.<br/>
Franco Alvarado: this is from tag review<br/>
… they thought this contradicted something in our docs<br/>
… and this is not possible in css today<br/>
Brady Duga: there is a contradiction. I don’t like this use case, because it’s not talking about functionality<br/>
… we’re talking about a specific technology. that’s dictating a solution.<br/>
… practically, having this is not going to be feasible<br/>
… we could ditch the use case<br/>
… implementing this would be a nightmare<br/>
Franco Alvarado: that sounds good to me<br/>
Ric Wright: +1 duga<br/>
Franco Alvarado: the requirement is something that’s not possible on the web<br/>
… I could see something with floats if you’re stitching together across spreads<br/>
… it seems like we don’t need to specify<br/>
Ivan Herman: I agree with brady that we should separate the implementation from the use case; it should be reformulated without reference to css<br/>
… the fact that it can’t be done on the web today is a sad reality,but it doesn’t mean that it can’t be a use case<br/>
… maybe we can convince css folks it’s of interest, or the superdom :)<br/>
… we should not remove a use case because it can’t be implemented<br/>
Bill Kasdorf: +1 to Ivan<br/>
Luc Audrain: there’s an issue between the use case and the example<br/>
… there’s a question about multiple resources in the same rendering<br/>
… but the counters thing is very important; doesn’t talk about rendering<br/>
… it’s strange to mix these things<br/>
… but I agree with ivan, we should not delete the use case<br/>
Brady Duga: does the use case require that this happen automatically?<br/>
… or is it good enough to be able to specify what those numbers should be?<br/>
… automatic or not?<br/>
Bill Kasdorf: this is a common issue wrt footnotes, endnotes, and references, but imo they can be explicit in the content per duga<br/>
</details>

**Comment by atyposh** [comment]
It is unreasonable to expect both
* Every resource of a web publication is completely independent of every other, and
* The resources should have enough awareness of each other to support CSS numbering across themselves.

As an author of a 15-chapter book (a WP consisting of 15 chapter resources) I should accept that the HTML/CSS of each chapter resource needs to be hard-coded (or populated with a simple build tool) with its chapter number, shouldn't I?

**Comment by llemeurfr** [comment]
Wouldn't a smart system use the reading order to infer that the last "page" number of a resource (totally dynamic because Web Publications are reflowable) is incremented by 1 for the first page of the next resource?

**Comment by atyposh** [comment]
> Wouldn't a smart system use the reading order to infer that the last "page" number of a resource (totally dynamic because Web Publications are reflowable) is incremented by 1 for the first page of the next resource?

@llemeurfr, indeed a WP UA should do this for dynamic (reflowed) page numbers (as most EPUB readers currently do). However, the CSS counter issue is more complicated. It's about dynamically generating list counters within the content, AFAIK. 

For example, imagine a legal document marked up with chapters, sections, subsections, and paragraphs. Every paragraph would have a CSS-generated label like "12.5.3.2". The "12" is the chapter number. If every chapter in the WP is its own document, then the CSS counter logic would either:
* Need to be aware of the preceding siblings (problematic if every resource is completely independent of the others)
* Need to be hardcoded (or built) such that the CSS counter is seeded with the "12" and counts automatically only within the chapter document
