### ISSUE TITLE
Who defines "reasonable use"?

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#79]
Who defines reasonable use? Do we need a requirement that does more to describe what reasonable use means to a PWP and its publishers?

“Bridget buys (rather than subscribes to) a PWP. She expects to have permanent access to that PWP and to be able to make reasonable use of it.” -- http://w3c.github.io/dpub-pwp-ucr/#r_process

**Comment by TzviyaSiegman** [comment]
@BillKasdorf @llemeurfr Please provide clearer language. Are you using the term "reasonable use" in a legal sense? If so, please provide a link. If not, let's find a term that is a little less vague.

**Comment by BorisAnthony** [comment]
Legal term would be "Fair Use" I believe. Here is [info on the U.S. Copyright Fair Use legal doctrine](http://www.copyright.gov/fair-use/more-info.html).

**Comment by baldurbjarnason** [comment]
This might have to be a bit vague and generic because 'reasonable use' in copyright terms is incredibly complex and varied. Fair Use is a US legal concept, not an international one. UK and Canada have Fair Dealing. Other countries just outline specific exceptions that can vary enormously. And yet other countries 'reasonable use' might be defined through collective bargaining (i.e. in Iceland many instances of reasonable use are defined through negotiations with the writer's union or The Performing Rights Society of Iceland).

**Comment by lrosenthol** [comment]
I removed that use case from [branch](https://github.com/w3c/dpub-pwp-ucr/tree/dedupe) as it has nothing to do with a use case for PWP itself.

**Comment by llemeurfr** [comment]
I agree that this requirement does not correspond to any practical use case (there is no PWP related "solution" to this). Therefore +1 for the removal.
