### ISSUE TITLE
Contradictory requirements in distribution?

### ISSUE THREAD

**Issue by hlflanagan** [w3c/dpub-pwp-ucr#85]
"Slicendice Publishing publishes many PWPs, some of which are different versions or subsets or combinations of others. Slicendice needs not only to be able to uniquely identify each unique PWP but also to identify each "copy" or "delivery" ("item") of each of those PWPs so that it can track "what" has been sold and "how many" of each one have been sold. (See also "There should be a way to uniquely identify a publication regardless of its state")" http://w3c.github.io/dpub-pwp-ucr/#r_process

seems to contradict
"Simply distributing or sharing a PWP to multiple destinations and devices should not result in multiple versions of the PWP. Those items should not be different versions of the source PWP unless they contain modifications that make them different PWPs." -- http://w3c.github.io/dpub-pwp-ucr/#r_distro

**Comment by BillKasdorf** [comment]
The issue is that somebody (I forget who)--focusing on retail--wanted to be able to track how many _copies_ of a given PWP are sold. So that implied that there needs to be a unique identifier for the PWP, which doesn't change just based on the distribution, and a different unique identifier for each copy of that PWP. Although I did reword the suggested use case, I tried to reflect that concept.

However, I wonder if it would really make more sense to say ". . . uniquely identify each unique PWP but also to _enumerate_ [rather than "identify"] each "copy" or "delivery" ("item"). . . ." This is a case of getting down to the absolute most granular level of the FRBR model.

**Comment by llemeurfr** [comment]
In a retail or loan process, tracking what has been delivered should be done at the application level (e-commerce / ILS), therefore I finally don't see why it would have consequences on the PWP individual item. The only content customization I know of has to do with watermarking, package customization happens in case of inclusion of a personal usage licence in the file delivered,  but this is another story. Therefore if there is no clear souvenir of why this 'Slicendice' UC is here, I propose to remove it (from  http://w3c.github.io/dpub-pwp-ucr/#r_process)

**Comment by iherman** [comment]
Proposed solution: remove that UC
